version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
  pre_build:
    commands:
      - pyton3 -m pip install -r requirements.txt
  build:
    commands:
      - echo 'Build complete'
  post_build:
    commands:
      - python3 -m pytest --junitxml=tests/results.xml

reports:
  pytest_reports:
    files:
      - results.xml
    base-directory: tests
    file-format: JUNITXML

artifacts:
  files:
    - '**/*'
  base_directory: base location
  name: panel-task-artifact
